### ISSUE TITLE
Wrapper compilation error for 20.04 (template argument deduction and substitution fail)

### ISSUE THREAD

**Issue by matthewoots** [berndpfrommer/basalt_ros1#10]
Hi there, thank you for your wrapper, but I've encountered errors on **Ubuntu 20.04** during compilation.
I don't know whether this would be helpful, but I'm using 
- libboost-all-dev = 1.71.0.0ubuntu2
- gcc and g++ = 9.3.0

Mainly **boost::irange** and **std::max** which is weird since they are default library functions, and the template argument deduction and substitution fail for them.

1. **irange** -> viz_flow_node.cpp
```
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/viz_flow_node.cpp: In member function ‘void VizFlow::flowCallback(const ConstPtr&, const ConstPtr&)’:
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/viz_flow_node.cpp:43:70: error: no matching function for call to ‘irange(long unsigned int, std::vector<basalt_vio_ros1_msgs::ObservationMap_<std::allocator<void> >, std::allocator<basalt_vio_ros1_msgs::ObservationMap_<std::allocator<void> > > >::size_type)’
   43 |    for (const auto obs_idx : irange(0ul, optFlow->observations.size())) {
      |                                                                      ^
In file included from /home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/viz_flow_node.cpp:11:
/usr/include/boost/range/irange.hpp:236:5: note: candidate: ‘template<class Integer> boost::integer_range<Integer> boost::irange(Integer)’
  236 |     irange(Integer last)
      |     ^~~~~~
/usr/include/boost/range/irange.hpp:236:5: note:   template argument deduction/substitution failed:
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/viz_flow_node.cpp:43:70: note:   candidate expects 1 argument, 2 provided
   43 |    for (const auto obs_idx : irange(0ul, optFlow->observations.size())) {
      |  
```
2. **max** -> image_subscriber.cpp
```
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/image_subscriber.cpp: In member function ‘void basalt_ros1::ImageSubscriber::callback(const ImageConstPtr&, const ImageConstPtr&)’:
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/image_subscriber.cpp:73:45: error: no matching function for call to ‘max(tbb::concurrent_bounded_queue<std::shared_ptr<basalt::OpticalFlowInput> >::size_type, long int&)’
   73 |     max_q_ = std::max(queue_->size(), max_q_);
      |                                             ^
In file included from /usr/include/c++/9/memory:62,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/include/basalt/optical_flow/optical_flow.h:37,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/include/basalt_ros1/image_subscriber.h:6,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/image_subscriber.cpp:5:
/usr/include/c++/9/bits/stl_algobase.h:222:5: note: candidate: ‘template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)’
  222 |     max(const _Tp& __a, const _Tp& __b)
      |     ^~~
/usr/include/c++/9/bits/stl_algobase.h:222:5: note:   template argument deduction/substitution failed:
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/image_subscriber.cpp:73:45: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘long int’)
   73 |     max_q_ = std::max(queue_->size(), max_q_);
      |  
```
3. **max** -> imu_subscriber.cpp
```
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/imu_subscriber.cpp: In member function ‘void basalt_ros1::IMUSubscriber::callback_combined(const ImuConstPtr&)’:
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/imu_subscriber.cpp:139:45: error: no matching function for call to ‘max(tbb::concurrent_bounded_queue<std::shared_ptr<basalt::ImuData> >::size_type, long int&)’
  139 |     max_q_ = std::max(queue_->size(), max_q_);
      |                                             ^
In file included from /usr/include/c++/9/bits/specfun.h:45,
                 from /usr/include/c++/9/cmath:1927,
                 from /usr/include/c++/9/complex:44,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/thirdparty/eigen/Eigen/Core:96,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/thirdparty/eigen/Eigen/Dense:1,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/thirdparty/Sophus/sophus/rotation_matrix.hpp:7,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/thirdparty/Sophus/sophus/so3.hpp:7,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/thirdparty/Sophus/sophus/se3.hpp:7,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/include/basalt/utils/sophus_utils.hpp:42,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/include/basalt/imu/imu_types.h:41,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/include/basalt_ros1/imu_subscriber.h:7,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/imu_subscriber.cpp:5:
/usr/include/c++/9/bits/stl_algobase.h:222:5: note: candidate: ‘template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)’
  222 |     max(const _Tp& __a, const _Tp& __b)
      |     ^~~
/usr/include/c++/9/bits/stl_algobase.h:222:5: note:   template argument deduction/substitution failed:
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/imu_subscriber.cpp:139:45: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘long int’)
  139 |     max_q_ = std::max(queue_->size(), max_q_);
      |
```

**Comment by matthewoots** [comment]
gcc and g++ version = 7.5.0 version reports the same error too
```
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/imu_subscriber.cpp: In member function ‘void basalt_ros1::IMUSubscriber::callback_accel(const ImuConstPtr&)’:
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/imu_subscriber.cpp:101:49: error: no matching function for call to ‘max(tbb::concurrent_bounded_queue<std::shared_ptr<basalt::ImuData> >::size_type, long int&)’
         max_q_ = std::max(queue_->size(), max_q_);

In file included from /usr/include/c++/7/functional:64:0,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/thirdparty/eigen/Eigen/Core:281,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/thirdparty/eigen/Eigen/Dense:1,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/thirdparty/Sophus/sophus/rotation_matrix.hpp:7,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/thirdparty/Sophus/sophus/so3.hpp:7,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/thirdparty/Sophus/sophus/se3.hpp:7,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/include/basalt/utils/sophus_utils.hpp:42,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt/thirdparty/basalt-headers/include/basalt/imu/imu_types.h:41,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/include/basalt_ros1/imu_subscriber.h:7,
                 from /home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/imu_subscriber.cpp:5:

/usr/include/c++/7/bits/stl_algo.h:3468:5: note: candidate: template<class _Tp, class _Compare> constexpr _Tp std::max(std::initializer_list<_Tp>, _Compare)
     max(initializer_list<_Tp> __l, _Compare __comp)
     ^~~
/usr/include/c++/7/bits/stl_algo.h:3468:5: note:   template argument deduction/substitution failed:
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/image_subscriber.cpp:73:45: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘int’
     max_q_ = std::max(queue_->size(), max_q_);
```

while image subscriber shows more promising conflict message 
```
/usr/include/c++/7/bits/stl_algobase.h:265:5: note:   template argument deduction/substitution failed:
/home/ubuntu/catkin_ws/src/basalt_ros/basalt_ros1/src/image_subscriber.cpp:73:45: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘long int’)
     max_q_ = std::max(queue_->size(), max_q_);
```

**Comment by matthewoots** [comment]
Solved it! but I will report the performance, better to keep this open for now, https://github.com/google/pik/issues/41 also have some issues, it should be compiler related.

Solved the issues with type casting, files to modify
```
        modified:   src/image_subscriber.cpp
	modified:   src/imu_subscriber.cpp
	modified:   src/optical_flow_subscriber.cpp
	modified:   src/viz_flow_node.cpp
```

Usually it would around these 2 lines, I hope I'm doing it right
```
-    max_q_ = std::max(queue_->size(), max_q_);
+    max_q_ = std::max(queue_->size(), (int)max_q_);

&&

-  for (const auto obs_idx : irange(0ul, msg->observations.size())) {
+  for (const auto obs_idx : irange(0, (int)msg->observations.size())) {
     const auto& msg_obs = msg->observations[obs_idx];
     auto& data_obs = data->observations[obs_idx];
-    for (const auto kp_idx : irange(0ul, msg_obs.keypoints.size())) {
+    for (const auto kp_idx : irange(0, (int)msg_obs.keypoints.size())) {
```

**Comment by berndpfrommer** [comment]
Hmm, I just compiled on ROS noetic under Ubuntu 20.04,gcc version 9.3.0, no problem. What's different between our build environments?

**Comment by matthewoots** [comment]
I've managed to get it to work on my 18.04 on my desktop but for this test on 20.04, I'm using a raspberry pi zero clone (banana pi m2 zero) with 20.04, using armhf.

**Comment by berndpfrommer** [comment]
OK, so is armhf the difference? I don't have the environment to build on that right now but may have in two months.

**Comment by matthewoots** [comment]
Don't worry about it, I've got a Xavier, I'll try compiling on it tomorrow and see whether the problem persist, it's running similar to 18.04.

**Comment by berndpfrommer** [comment]
Is that a 32 bit system you are compiling on?

**Comment by matthewoots** [comment]
Yeah it's a 32bit ARM Cortex A7

**Comment by berndpfrommer** [comment]
That's the problem: 32 bit size_t

**Comment by matthewoots** [comment]
garrhhhh I see, okay then that solves it, though do you think it would affect overall performance in any way?

**Comment by berndpfrommer** [comment]
you mean runtime performance or tracking accuracy? Basalt is pretty efficient, but whether it would run well on 32bits, I'm not sure. Would certainly require some parameter tuning.

**Comment by berndpfrommer** [comment]
I pushed a fix that may make it compile on 32bit arm. Could you please see if it builds on your machine?

**Comment by matthewoots** [comment]
Hi @berndpfrommer , thank you so much for helping out with the 32bit system, I'll pull it tomorrow when I'm with my equipment.

**Comment by matthewoots** [comment]
Hi @berndpfrommer, ROS1 compiles it well without any complaint, thank you for the fix, you can close the issue
`32Bit system compatibility fix` is b56bb34f33beb23855dfd697735526b9f05f08a6
Status of successful compilation
```
Starting  >>> basalt                                                                                                                 
Starting  >>> basalt_vio_ros1_msgs                                                                                                   
Finished  <<< basalt_vio_ros1_msgs                [ 6.5 seconds ]                                                                    
Finished  <<< basalt                              [ 12.1 seconds ]                                                                   
Starting  >>> basalt_ros1                                                                                                            
Finished  <<< basalt_ros1                         [ 11.7 seconds ]                                                                   
[build] Summary: All 3 packages succeeded!                                                                                           
[build]   Ignored:   5 packages were skipped or are blacklisted.                                                                     
[build]   Warnings:  None.                                                                                                           
[build]   Abandoned: None.                                                                                                           
[build]   Failed:    None.                                                                                                           
[build] Runtime: 25.4 seconds total.
```

**Comment by berndpfrommer** [comment]
@matthewoots thanks for testing!
Fixed with https://github.com/berndpfrommer/basalt_ros1/commit/b56bb34f33beb23855dfd697735526b9f05f08a6
